words = [
    "CCF",
    "CPDR",
    "CPIR",
    "DAA",
    "DJNZ",
    "EXX",
    "INDR",
    "INIR",
    "LDD",
    "LDDR",
    "LDI",
    "LDIR",
    "OTDR",
    "OTIR",
    "OUTD",
    "OUTI",
    "RETI",
    "RETN",
    "RLA",
    "RLC",
    "RLCA",
    "RLD",
    "RRA",
    "RRC",
    "RRCA",
    "RRD",
    "SBC",
    "SCF",
    "SRL",
    "mmu",
    "nnnn",
    "nop",
    "sicp",
    "𝑓",
]
